build:
    nodes:
        node-with-functional-tests:
            environment:
                google_chrome:
                    use_latest: true
                selenium: true
        coverage:
            tests:
                override:
                    - command: npm test
                      coverage:
                          file: coverage/clover.xml
                          format: clover
